// Generated by scripts/build_data.py — course pages /api/refresh may fetch, per university.
export default {
 "Imperial College London": [
  "https://www.imperial.ac.uk/study/courses/postgraduate-taught/2027/computing/",
  "https://www.imperial.ac.uk/study/courses/postgraduate-taught/2027/artificial-intelligence-machine-learning/"
 ],
 "University of Cambridge": [
  "https://www.postgraduate.study.cam.ac.uk/courses/directory/cscsmpacs",
  "https://www.postgraduate.study.cam.ac.uk/courses/directory/egegmpmsl"
 ],
 "King's College London": [
  "https://www.kcl.ac.uk/study/postgraduate-taught/courses/advanced-computing-msc",
  "https://www.kcl.ac.uk/study/postgraduate-taught/courses/artificial-intelligence-msc"
 ],
 "University of Manchester": [
  "https://www.manchester.ac.uk/study/masters/courses/list/21573/msc-advanced-computer-science/",
  "https://www.manchester.ac.uk/study/masters/courses/list/21574/msc-artificial-intelligence/"
 ],
 "University of Bristol": [
  "https://www.bristol.ac.uk/study/outreach/virtual-resources-for-students/access-virtual-resources/virtual-resources/computer-science-resources/",
  "https://www.bristol.ac.uk/study/postgraduate/taught/msc-artificial-intelligence/",
  "https://www.bristol.ac.uk/study/postgraduate/taught/msc-immersive-technologies-virtual-and-augmented-reality/"
 ],
 "University of Warwick": [
  "https://warwick.ac.uk/study/postgraduate/courses/msc-computer-science/",
  "https://warwick.ac.uk/study/postgraduate/courses/msc-applied-artificial-intelligence/"
 ],
 "University of Birmingham": [
  "https://www.birmingham.ac.uk/study/postgraduate/subjects/computer-science-and-data-science-courses/advanced-computer-science-msc",
  "https://www.birmingham.ac.uk/study/postgraduate/subjects/computer-science-and-data-science-courses/artificial-intelligence-machine-learning-msc",
  "https://www.birmingham.ac.uk/study/postgraduate/subjects/computer-science-and-data-science-courses/human-computer-interaction-msc"
 ],
 "University of Leeds": [
  "https://courses.leeds.ac.uk/F753/advanced_computer_science_msc"
 ],
 "University of Glasgow": [
  "https://www.gla.ac.uk/postgraduate/taught/computingscience/",
  "https://www.gla.ac.uk/postgraduate/taught/humancomputerinteraction/"
 ],
 "University of Sheffield": [
  "https://sheffield.ac.uk/postgraduate/taught/courses/2027/advanced-computer-science-msc",
  "https://sheffield.ac.uk/postgraduate/taught/courses/2027/artificial-intelligence-msc"
 ],
 "Durham University": [
  "https://www.durham.ac.uk/study/postgraduate/taught-degrees/your-choices/computer-science/"
 ],
 "University of Southampton": [
  "https://www.southampton.ac.uk/courses/advanced-computer-science-masters-msc",
  "https://www.southampton.ac.uk/courses/artificial-intelligence-masters-msc"
 ],
 "University of Bath": [
  "https://www.bath.ac.uk/courses/postgraduate-2027/taught-postgraduate-courses/msc-computer-science/",
  "https://www.bath.ac.uk/courses/postgraduate-2027/taught-postgraduate-courses/msc-artificial-intelligence/",
  "https://www.bath.ac.uk/courses/postgraduate-2019/taught-postgraduate-courses/msc-human-computer-interaction/"
 ],
 "University of Exeter": [
  "https://www.exeter.ac.uk/masters-degrees/msc-advanced-computer-science/"
 ],
 "University of Liverpool": [
  "https://www.liverpool.ac.uk/courses/advanced-computer-science-with-a-year-in-industry-msc",
  "https://www.liverpool.ac.uk/courses/advanced-data-science-and-artificial-intelligence-msc"
 ],
 "University of York": [
  "https://www.york.ac.uk/study/postgraduate-taught/courses/msc-advanced-computer-science/",
  "https://www.york.ac.uk/study/postgraduate-taught/courses/msc-human-centred-interactive-technologies/"
 ],
 "University of Strathclyde": [
  "https://www.strath.ac.uk/courses/postgraduatetaught/advancedcomputerscience/",
  "https://www.strath.ac.uk/courses/postgraduatetaught/artificialintelligenceapplications/"
 ],
 "University of Sussex": [
  "https://www.sussex.ac.uk/study/masters/courses/advanced-computer-science-msc",
  "https://www.sussex.ac.uk/study/masters/courses/artificial-intelligence-and-adaptive-systems-msc"
 ],
 "Heriot-Watt University": [
  "https://www.hw.ac.uk/study/subjects/computer-science",
  "https://www.hw.ac.uk/study/postgraduate/artificial-intelligence"
 ],
 "Aston University": [
  "https://www.aston.ac.uk/study/courses/advanced-computer-science-msc/april-2027"
 ],
 "University of Greenwich": [
  "https://www.gre.ac.uk/postgraduate-courses/engsci/computer-science-msc"
 ],
 "Wrexham University": [
  "https://wrexham.ac.uk/courses/postgraduate-courses/computer-science/"
 ],
 "Edge Hill University": [
  "https://www.edgehill.ac.uk/course/computing-msc/",
  "https://www.edgehill.ac.uk/course/data-science-and-artificial-intelligence/"
 ],
 "University of Chester": [
  "https://www.chester.ac.uk/study/course-search/advanced-computer-science-msc/"
 ],
 "University of Sunderland": [
  "https://www.sunderland.ac.uk/postgraduate/msc-computing"
 ],
 "University of Staffordshire": [
  "https://www.staffs.ac.uk/course/computer-science-msc"
 ],
 "Keele University": [
  "https://www.keele.ac.uk/study/postgraduatestudy/postgraduatecourses/computerscience/",
  "https://www.keele.ac.uk/study/postgraduatestudy/postgraduatecourses/artificialintelligenceanddatascience/"
 ],
 "Bangor University": [
  "https://www.bangor.ac.uk/courses/postgraduate-taught/advanced-computer-science-msc"
 ],
 "Coventry University": [
  "https://www.coventry.ac.uk/course-structure/pg/ees/computer-science-msc/",
  "https://www.coventry.ac.uk/course-structure/pg/ees/artificial-intelligence-human-factors-msc/"
 ],
 "Manchester Metropolitan Univ.": [
  "https://www.mmu.ac.uk/study/postgraduate/course/msc-computer-science",
  "https://www.mmu.ac.uk/study/postgraduate/course/msc-artificial-intelligence"
 ],
 "University of Bradford": [
  "https://www.bradford.ac.uk/courses/pg/applied-computer-science-artificial-intelligence"
 ],
 "Sheffield Hallam University": [
  "https://www.shu.ac.uk/courses/computing/msc-computing/full-time",
  "https://www.shu.ac.uk/courses/computing/msc-artificial-intelligence/full-time"
 ],
 "Birmingham City University": [
  "https://www.bcu.ac.uk/courses/computer-science-msc-2027-28",
  "https://www.bcu.ac.uk/courses/artificial-intelligence-msc-2027-28"
 ],
 "University of Wolverhampton": [
  "https://www.wlv.ac.uk/courses/msc-computer-science/",
  "https://www.wlv.ac.uk/courses/msc-artificial-intelligence/"
 ],
 "University of Northampton": [
  "https://www.northampton.ac.uk/courses/computing-msc/"
 ],
 "University of Portsmouth": [
  "https://www.port.ac.uk/study/courses/postgraduate-taught/msc-computer-science",
  "https://www.port.ac.uk/study/courses/postgraduate-taught/msc-artificial-intelligence-and-machine-learning"
 ],
 "Middlesex University": [
  "https://www.mdx.ac.uk/courses/postgraduate/computer-science-msc-honours/"
 ],
 "University of East London": [
  "https://www.uel.ac.uk/postgraduate/courses/msc-computer-science",
  "https://www.uel.ac.uk/postgraduate/courses/msc-artificial-intelligence"
 ],
 "University of Brighton": [
  "https://www.brighton.ac.uk/courses/study/computer-science-msc.aspx",
  "https://www.brighton.ac.uk/courses/study/user-experience-design-msc-pgcert-pgdip.aspx"
 ],
 "Leeds Beckett University": [
  "https://www.leedsbeckett.ac.uk/courses/advanced-computer-science-msc/",
  "https://www.leedsbeckett.ac.uk/courses/ai-data-science-msc/"
 ],
 "Birkbeck, Univ. of London": [
  "https://www.bbk.ac.uk/courses/postgraduate/computer-science"
 ],
 "University of East Anglia": [
  "https://www.uea.ac.uk/course/postgraduate/msc-computing-science"
 ],
 "Northumbria University": [
  "https://www.northumbria.ac.uk/study-at-northumbria/courses/msc-advanced-computer-science-dtfava6/",
  "https://www.northumbria.ac.uk/study-at-northumbria/courses/msc-artificial-intelligence-dtfari6/",
  "https://www.northumbria.ac.uk/study-at-northumbria/courses/msc-human-computer-interaction-dtfhct6/"
 ],
 "Edinburgh Napier University": [
  "https://www.napier.ac.uk/courses/msc-computing-postgraduate-fulltime",
  "https://www.napier.ac.uk/courses/msc-user-experience-design-postgraduate-fulltime"
 ],
 "Swansea University": [
  "https://www.swansea.ac.uk/postgraduate/taught/maths-comp-sci/computer-science/msc-advanced-computer-science/"
 ],
 "University of Hull": [
  "https://www.hull.ac.uk/study/postgraduate-taught/courses/advanced-computer-science-msc",
  "https://www.hull.ac.uk/study/postgraduate-taught/courses/artificial-intelligence-and-data-science-msc"
 ],
 "Queen Mary Univ. of London": [
  "https://www.qmul.ac.uk/postgraduate/taught/coursefinder/courses/artificial-intelligence-msc/"
 ],
 "University of St Andrews": [
  "https://www.st-andrews.ac.uk/subjects/computer-science/artificial-intelligence-msc/",
  "https://www.st-andrews.ac.uk/subjects/computer-science/human-computer-interaction-msc/"
 ],
 "Lancaster University": [
  "https://www.lancaster.ac.uk/sci-tech/pgt-my-offer/ai/index.php"
 ],
 "University of Surrey": [
  "https://www.surrey.ac.uk/postgraduate/artificial-intelligence-msc"
 ],
 "Brunel University of London": [
  "https://www.brunel.ac.uk/study/courses/artificial-intelligence-msc",
  "https://www.brunel.ac.uk/study/courses/human-ai-interaction-msc"
 ],
 "Abertay University": [
  "https://www.abertay.ac.uk/course-search/postgraduate-taught/applied-artificial-intelligence-and-user-experience/"
 ],
 "University of Plymouth": [
  "https://www.plymouth.ac.uk/courses/postgraduate/msc-artificial-intelligence",
  "https://www.plymouth.ac.uk/courses/postgraduate/ma-experience-design"
 ],
 "University of Stirling": [
  "https://www.stir.ac.uk/courses/pg-taught/artificial-intelligence/"
 ],
 "Liverpool John Moores Univ.": [
  "https://www.ljmu.ac.uk/study/courses/postgraduates/2027/36223-artificial-intelligence-machine-learning-msc"
 ],
 "University of Salford": [
  "https://www.salford.ac.uk/courses/postgraduate/artificial-intelligence"
 ],
 "De Montfort University": [
  "https://www.dmu.ac.uk/study/courses/postgraduate-courses/artificial-intelligence-msc/artificial-intelligence-msc.aspx"
 ],
 "UWE Bristol": [
  "https://courses.uwe.ac.uk/I4001/artificial-intelligence"
 ],
 "University of Westminster": [
  "https://www.westminster.ac.uk/computer-science-and-engineering-data-science-and-informatics-courses/2027-28/september/full-time/applied-artificial-intelligence-msc"
 ],
 "Goldsmiths, Univ. of London": [
  "https://www.gold.ac.uk/pg/msc-applied-artificial-intelligence/"
 ],
 "Royal Holloway, Univ. of London": [
  "https://www.royalholloway.ac.uk/studying-here/postgraduate/computer-science/artificial-intelligence"
 ],
 "Queen's University Belfast": [
  "https://www.qub.ac.uk/courses/postgraduate-taught/2026/artificial-intelligence-msc/"
 ],
 "Univ. of the West of Scotland": [
  "https://www.uws.ac.uk/study/postgraduate/postgraduate-course-search/artificial-intelligence"
 ],
 "Oxford Brookes University": [
  "https://www.brookes.ac.uk/courses/postgraduate/artificial-intelligence"
 ],
 "Anglia Ruskin University": [
  "https://www.aru.ac.uk/study/postgraduate/artificial-intelligence"
 ],
 "Solent University": [
  "https://www.solent.ac.uk/courses/postgraduate/applied-ai-and-data-science-msc"
 ],
 "University of Nottingham": [
  "https://www.nottingham.ac.uk/pgstudy/course/taught/human-computer-interaction-msc"
 ],
 "Loughborough University": [
  "https://lboro.ac.uk/study/postgraduate/masters-degrees/user-experience-design/"
 ],
 "University for the Creative Arts": [
  "https://www.uca.ac.uk/study/courses/msc-human-computer-interaction/"
 ],
 "University of Lancashire (UCLan)": [
  "https://www.lancashire.ac.uk/postgraduate/courses/user-experience-ux-design-msc"
 ],
 "University of Roehampton": [
  "https://www.roehampton.ac.uk/study/postgraduate-taught-courses/computing/",
  "https://www.roehampton.ac.uk/study/postgraduate-taught-courses/artificial-intelligence/"
 ],
 "Cranfield University": [
  "https://www.cranfield.ac.uk/courses/taught/applied-artificial-intelligence"
 ],
 "Canterbury Christ Church University": [
  "https://www.canterbury.ac.uk/study-here/courses/computer-science"
 ],
 "University of Suffolk": [
  "https://www.uos.ac.uk/study/msc-computer-science/",
  "https://www.uos.ac.uk/study/msc-data-science-artificial-intelligence/"
 ],
 "Bath Spa University": [
  "https://www.bathspa.ac.uk/courses/pg-computer-science/",
  "https://www.bathspa.ac.uk/courses/pg-artificial-intelligence/"
 ],
 "Buckinghamshire New University": [
  "https://www.bucks.ac.uk/courses/postgraduate/msc-computer-science",
  "https://www.bucks.ac.uk/courses/postgraduate/msc-artificial-intelligence"
 ]
};
